### ISSUE TITLE
add list of browsers to package.json

### ISSUE THREAD

**Issue by kvutien** [talves/netlify-cra-env-vars#13]
Aswesome repo, thanks.

* FYI, I cloned it, `cd`'ed to the folder, did `npm install` and `npm start`
* It asked me whether I want to add a list of recommended browsers, I said "yes" and the demo worked.
* You may want to add the following to your `package.json` to skip this undocumented question ?
```
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by talves** [comment]
Thanks for the heads up. I think this is a tooling recommend more than a dependency. I'll leave it to not be opinionated on the browsers I would allow vs what others find they want. I may review what CRA recommends later, so I'm glad you let me know. Hope you have great luck with Netlify
